spring.application.name=table-booking
server.port=8080
spring.data.mongodb.uri=mongodb://localhost:27017/tablebooking

jwt.secret=K8xP2#mN9$qR7&vT1@wZ5^cF6*yH3!jL4%kM0&nB8(vC7$dX9*sP2#rT5&hY8^
jwt.expiration=3600000
