package com.example.floweandgift.scripts;

import com.example.floweandgift.model.Product;
import com.example.floweandgift.model.Product.ProductType;
import com.example.floweandgift.service.ProductService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

import java.util.Arrays;

@Component
public class SeedNewProductsExample implements CommandLineRunner {

    @Autowired
    private ProductService productService;

    @Override
    public void run(String... args) throws Exception {
        Product p1 = new Product();
        p1.setName("Sample Flower Bouquet");
        p1.setSlug("sample-flower-bouquet");
        p1.setDescription("A beautiful bouquet of mixed flowers");
        p1.setPrice(29.99);
        p1.setStock(100);
        p1.setType(ProductType.FLOWER);
        p1.setCategoryId("flowers");
        p1.setImages(Arrays.asList("image1.jpg", "image2.jpg"));
        p1.setOccasion("Birthday");
        p1.setColor("Red");
        p1.setIsFresh(true);
        p1.setTags(Arrays.asList("flower", "bouquet", "birthday"));

        // No need to set ID explicitly; will be autogen before save

        productService.addProduct(p1);

        System.out.println("Sample product seeded with autogenerated ID: " + p1.getId());
    }
}
